window.textbooks = {
  "6th Class": {
    "Telugu": [
      "మన ఊరు – మనం",
      "ఊరి దీవెన",
      "పాట",
      "సరదా సమయం",
      "చిన్నారి భూమిక",
      "మచ్చలు",
      "మనుషులే దేవుళ్లు",
      "శ్రీకృష్ణ లీలలు"
    ],
    "Hindi": [
      "वह चिड़िया जो",
      "बचपन",
      "नादान दोस्त",
      "चाँद से थोड़ी सी गप्पें",
      "अक्षरों का महत्व",
      "पार नज़र के",
      "साथी हाथ बढ़ाना",
      "ऐसे-ऐसे",
      "टिकट एल्बम",
      "झाँसी की रानी"
    ],
    "English 1": [
      "Who Did Patrick’s Homework?",
      "I Want Peace",
      "I Wonder",
      "The Selfish Giant",
      "A Lesson for All",
      "The Bond of Love",
      "The Naughty Boy",
      "The Monkey and the Crocodile",
      "The School for Sympathy",
      "What Can a Dollar and Eleven Cents Do?"
    ],
    "English 2": [],
    "Math": [
      "Knowing Our Numbers",
      "Whole Numbers",
      "Basic Geometrical Ideas",
      "Playing with Numbers",
      "Understanding Elementary Shapes",
      "Integers",
      "Fractions",
      "Decimals",
      "Data Handling",
      "Mensuration",
      "Algebra",
      "Ratio and Proportion",
      "Symmetry",
      "Practical Geometry"
        ],
    "Math IIT": [
      "Tables, Squares and Cubes",
      "Knowing Our Numbers",
      "Roman Numerals",
      "Integers",
      "Fractions and Decimals",
      "Rational Numbers",
      "Factorization",
      "Linear Equations in One Variable",
      "Ratio and Proportion",
      "Square Roots and Cube Roots",
      "Simple Intrest, Time - Distance, Time - Work",
      "Whole Numbers",
    "Playing With Numbers",
    "LCM and HCF",
    "Inroduction to Algebra",
    "Algebraic Expressions",
    "Basic Geometrical Ideas",
    "Measures of lines and Angles",
    "Data Handling",
    "Exponents and Powers",
    "Perimeter and Area"
    ],
    "Physics": [
      "Our Food",
      "Sorting Materials into Groups",
      "Separation of Substances",
      "Changes Around Us",
      "Water",
      "Magnets",
      "Motion and Measurement"
    ],
   "Physics IIT & NEET": [
  "Units and Measurements: Assimilation 1 (Importance of Measurements, Physical Quantity and its Types, Unit)",
  "Units and Measurements: Assimilation 2 (Multiples and Sub-multiples)",
  "Units and Measurements: Assimilation 3 (Measurement of Length, Measurement of Area, Volume and Density)",
  "Kinematics: Assimilation 1 (Rest, Motion, Different Types of Motion, Distance and Displacement)",
  "Kinematics: Assimilation 2 (Speed, Velocity, Acceleration)",
  "Newton’s Laws of Motion: Assimilation 1 (Force, Effects of Force, Balanced and Unbalanced Forces, Newton’s First Law of Motion)",
  "Newton’s Laws of Motion: Assimilation 2 (Momentum, Newton’s Second Law, Newton’s Third Law and its Applications)",
  "Work, Energy and Power: Assimilation 1 (Work Done by a Force, Types of Work Done)",
  "Work, Energy and Power: Assimilation 2 (Energy, Kinds of Energy, Power)",
  "Heat: Assimilation 1 (Thermal Equilibrium, Heat and Temperature, Scales of Temperature)",
  "Light: Assimilation 1 (Light, Propagation of Light, Terms Related to Light, Reflection of Light, Laws of Reflection)",
  "Electronics: Assimilation 1 (Types of Images, Electric Charge, Process of Electrification, Conductors and Insulators)",
  "Electronics: Assimilation 2 (Electric Cell, Resistance, Series and Parallel Combination, Elements Used in Electrical Circuits)",
  "Magnetism: Assimilation 1 (Magnets, Types of Magnets, Magnetic Materials, Properties of Magnets)",
  "Magnetism: Assimilation 2 (Terms Used in Magnetism, Methods of Magnetization)"
],
    "Chemistry": [
      "Materials and Their Properties",
      "Separation of Substances",
      "Air Around Us"
    ],
  "Chemistry IIT & NEET": [
  "Nature of Chemistry: Assimilation 1 (Universe, Radiation, Matter)",
  "Nature of Chemistry: Assimilation 2 (Pure Substance, Characteristics of Pure Substance, Types of Pure Substance, Elements, Types of Elements, Compound, Mixtures)",
  "Nature of Chemistry: Assimilation 3 (Thrashing, Winnowing, Handpicking, Sieving, Sedimentation, Filtration, Distillation, Sublimation, Centrifugation)",
  "Language of Chemistry: Assimilation 1 (Symbols of Elements, Guidelines to Write the Symbols)",
  "Language of Chemistry: Assimilation 2 (Valency, Variable Valency)",
  "Language of Chemistry: Assimilation 3 (Ions, Types of Ions, Classification of Ions, Electrovalent Positive Radicals, Electrovalent Negative Radicals)",
  "Language of Chemistry: Assimilation 4 (Chemical Formula, Basic Rules for Writing Formula, Importance of Chemical Formula, Writing the Formula of Ionic Compounds)",
  "Basic Concepts of Chemistry: Assimilation 1 (Atom, Dalton’s Atomic Theory, Contradictions of Dalton’s Atomic Theory, Subatomic Particles, Representation of Element)",
  "Basic Concepts of Chemistry: Assimilation 2 (Isotopes, Characteristics of Isotopes, Types of Isotopes, Isobars, Isotones, Isodiaphers, Isoelectronic Species)",
  "Basic Concepts of Chemistry: Assimilation 3 (Law of Conservation of Mass, Law of Constant Proportions, Law of Multiple Proportions)",
  "Basic Concepts of Chemistry: Assimilation 4 (Chemical Reaction, Chemical Equation, Unbalanced Chemical Equation, Balanced Chemical Equation, Types of Chemical Reactions, Combination Reactions, Decomposition Reactions, Displacement Reactions, Double Displacement Reactions)",
  "Atomic Structure: Assimilation 1 (Introduction, Dalton’s Atomic Theory, Contradictions of Dalton’s Atomic Theory, Discovery of Subatomic Particles, Discovery of Electron – Properties, Discovery of Anode Rays – Properties, Discovery of Neutron)",
  "Chemical Bonding: Assimilation 1 (Definition of Chemical Bond, Explanation of the Formation of Chemical Bond)",
  "Acids, Bases and Salts: Assimilation 1 (Introduction, Definition of Acid, Preparation Methods of Acids, Physical and Chemical Properties of Acids, Definition of a Base, Preparation Methods of Bases, Physical and Chemical Properties of Bases, Acidity and Basicity)",
  "Allotropy of Carbon: Assimilation 1 (Introduction, Diamond, Graphite, Fullerenes, Graphene)",
  "Transformation of Substances: Assimilation 1 (Classification of Changes, Slow and Fast Changes, Reversible and Irreversible Changes, Desirable and Undesirable Changes, Periodic and Non-Periodic Changes, Physical and Chemical Changes)",
  "Transformation of Substances: Assimilation 2 (Characteristics of Physical Changes, Characteristics of Chemical Changes, Differences between Physical Change and Chemical Change, Examples of Physical and Chemical Changes)",
  "Water: Assimilation 1 (Introduction, Importance of Water, Role of Water, Physical Properties of Water, Sources of Water, Availability of Water for Human Consumption)",
  "Air: Assimilation 1 (Introduction, Composition of Air, Properties of Air, Characteristics of Air, Simple Experiments to Show the Properties of Air, Experiments to Show the Presence of Oxygen, Water Vapour, etc.)",
  "Air: Assimilation 2 (Fire Wood Oven, Kumpati, Kerosene Stove, To Show Oxygen is Necessary For Combustion, Uses of Different Constituents of Air, Significance of Nitrogen in Atmosphere, Symbiotic Bacteria, Oxygen – Significance in Atmosphere, Carbon Dioxide – Significance in Atmosphere, Green House Effect, Water Vapour – Significance in Atmosphere, Noble Gases – Significance)",
  "Apparatus in Chemical Laboratory: Assimilation 1 (Chemical Laboratory Apparatus)"
],
    "Biology": [
      "Components of Food",
      "Getting to Know Plants",
      "The Living World",
      "Plant World",
      "Animal World",
      "Our Environment"
    ],
    "Biology NEET": [
      "Nutrition in Plants",
      "Nutrition in Animals",
      "Weather, Climate & Adaptation",
      "Soil",
      "Respiration in Organisms",
      "Transportation in Animals and Plants",
      "Reproduction in Plants",
      "Forest-Our Lifeline"
    ],
    "Social": [
      "Our Earth in the Solar Syatem",
      "Maps",
      "Early Life to Settled Life",
      "Reading and Making Maps",
      "Globe – A Model of the Earth",
      "Land Forms - Andhra Pradesh",
      "India – Our Motherland",
      "Indian Rivers",
      "Major Domains of the Earth",
      "Andhra Pradesh: Land and Rivers",
      "Andhra Pradesh: Climate and Vegetation"
    ]
  },

  "7th Class": {
    "Telugu": [
      "పిల్లల పండుగ",
      "జన్మభూమి",
      "మా మావు",
      "ప్రకృతి మనిషి",
      "పల్లె ప్రస్థానం",
      "సముద్ర గమనం",
      "భగవంతుని దయ",
      "స్వాతంత్ర్య వీరుడు",
      "జ్ఞాన యోగా",
      "మన ఊరుని పండుగలు",
      "అన్నదాత",
      "విజ్ఞాన శాస్త్రవేత్త",
      "మన ఊరుని ఆటలు"
    ],
    "Hindi": [
      "हम पंछी उन्मुक्त गगन के",
      "दादी माँ",
      "हिमालय की बेटियाँ",
      "कठपुतली",
      "मिठाईवाला",
      "रक्त और हमारा शरीर",
      "पापा खो गए",
      "शाम - एक किसान",
      "चिड़िया की बच्ची",
      "अपूर्व अनुभव",
      "रहीम के दोहे",
      "कंचा",
      "एक तिनका"
    ],
    "English 1": [
      "Three Questions",
      "A Gift of Chappals",
      "The Desert",
      "The Cop and the Anthem",
      "Golu Grows a Nose",
      "I Want Something in a Cage",
      "Chandni",
      "The Bear Story",
      "A Tiger in the House"
    ],
    "English 2": [],
    "Math": [
      "Integers",
      "Fractions and Decimals",
      "Data Handling",
      "Simple Equations",
      "Lines and Angles",
      "The Triangle and its Properties",
       "Congruence of Triangles",
      "Comparing Quantities",
      "Rational Numbers",
      "Practical Geometry",
      "Perimeter and Area",
      "Algebraic Expressions",
      "Exponents and Powers",
      "Symmetry",
      "Visualizing Solid Shapes"
    ],
    "Math IIT": [
      "Number System",
      "Integers",
      "Fractions and Decimals",
      "Divisibility Rules",
      "Polygons",
      "Rational Numbers",
      "Linear Equations in One Variable",
      "Linear Equations in Two Variables",
      "Measures Lines and Angles",
      "Triangles",
      "Ratio and Proportions",
      "Formula and Their Uses",
      "Data Handling",
       "Congruency of Triangles",
      "Algebraic Expressions",
      "Algebraic Expressions LCM & HCF",
      "Factorisation",
      "Area and Perimeter",
      "Circles and Rings",
      "Exponents and Powers",
      "Progressions",
      "Mensuration",
      "Commercial Mathematics"
    ],
    "Physics": [
      "Heat",
      "Motion and Time",
      "Electric Current and Its Effects",
      "Winds, Storms and Cyclones",
      "Light"
    ],
   "Physics IIT & NEET": [
  "Units and Measurements: Assimilation 1 (Physical Quantity, Fundamental Physical Quantity, Derived Quantity, Unit, System of Units, Guidelines for Writing Units)",
  "Units and Measurements: Assimilation 2 (Multiple and Sub Multiples)",
  "Units and Measurements: Assimilation 3 (Mass, Length and Time, Its Units and Measurement)",
  "Units and Measurements: Assimilation 4 (Area, Measurement of Area)",
  "Units and Measurements: Assimilation 5 (Volume, Measurement of Volume)",
  "Units and Measurements: Assimilation 6 (Density, Relative Density or Specific Gravity)",
  "Units and Measurements: Assimilation 7 (Dimensional Formula, Dimensional Formula of Some Physical Quantities)",
  "Kinematics: Assimilation 1 (Rest, Motion, Different Kinds of Motion)",
  "Kinematics: Assimilation 2 (Distance and Displacement)",
  "Kinematics: Assimilation 3 (Speed, Types of Speed, Velocity, Types of Velocity)",
  "Kinematics: Assimilation 4 (Acceleration, Types of Acceleration)",
  "Kinematics: Assimilation 5 (Equation of Motion and Its Derivation)",
  "Newton’s Laws of Motion: Assimilation 1 (Force, Types of Forces, Effects of Force, Newton’s Law of Motion, Inertia, Types of Inertia)",
  "Newton’s Laws of Motion: Assimilation 2 (Momentum, Newton’s Second Law of Motion)",
  "Newton’s Laws of Motion: Assimilation 3 (Newton’s Third Law of Motion and Its Examples, Law of Conservation of Momentum, Applications of Conservation of Momentum)",
  "Newton’s Laws of Motion: Assimilation 4 (Forces on a Rigid Body, Moment of Force, Principle of Moments, Couple, Daily Life Applications)",
  "Work, Energy and Power: Assimilation 1 (Work Done by a Force, Calculation of Work Done)",
  "Work, Energy and Power: Assimilation 2 (Energy, Types of Energy, Law of Conservation of Energy, Energy Transformation)",
  "Work, Energy and Power: Assimilation 3 (Power, Practical Units of Power)",
  "Fluid Pressure: Assimilation 1 (Thrust, Pressure, Application of Pressure, Pressure in Fluids, Law of Liquid Pressure, Atmospheric Pressure, Pascal’s Law and Its Applications)",
  "Heat: Assimilation 1 (Thermal Equilibrium, Heat and Temperature, Measurement of Temperature, Scales of Temperature)",
  "Heat: Assimilation 2 (Transmission of Heat and Different Methods, Change of State, Latent Heat, Specific Heat)",
  "Electricity: Assimilation 1 (Electric Charge and Current, Resistance, Series and Parallel Combination of Resistances)",
  "Electricity: Assimilation 2 (Conductors and Insulators, Series and Parallel Combination of Bulbs, Electrical Energy and Power and Its Measurement, Heating Effect of Electric Current and Its Applications)"
],
    "Chemistry": [
      "Acids, Bases and Salts",
      "Physical and Chemical Changes",
      "Water: A Precious Resource",
      "Soil"
    ],
   "Chemistry IIT & NEET": [
  "States of Matter: Assimilation 1 (Matter, Properties of Matter, Classification of Matter, Comparative Study of Solids, Liquids and Gases, Plasma, Bose–Einstein Condensate)",
  "States of Matter: Assimilation 2 (Pure Substances, Elements, Types of Elements, Physical Properties of Metals and Non-Metals, Metalloids, Radioactive Elements, Compounds)",
  "States of Matter: Assimilation 3 (Measurable Properties of Gases, Measurement of Atmospheric Pressure, Boyle’s Law, Charles–Gay Lussac Law, Charles’ Law, Avogadro’s Law)",
  "Basic Concepts of Chemistry: Assimilation 1 (Atomic Mass, Atomic Weight, Gram Atomic Mass, Molecular Mass, Molecular Weight, Gram Molecular Mass, Mole Concept, Molar Mass, Gram Molar Volume, Loschmidt Number, Avogadro Number, Vapour Density)",
  "Basic Concepts of Chemistry: Assimilation 2 (Types of Chemical Reactions, Combination Reaction, Decomposition Reaction, Displacement Reaction, Double Displacement Reaction, Some Other Chemical Reactions)",
  "Basic Concepts of Chemistry: Assimilation 3 (Laws of Chemical Combinations, Law of Conservation of Mass, Law of Constant Proportions, Law of Multiple Proportions)",
  "Language of Chemistry: Assimilation 1 (Valency, Valency of Elements, Valency of Metals, Valency of Non-Metals, Variable Valency, Chemical Formulae of Compounds, Criss-Cross Method)",
  "Language of Chemistry: Assimilation 2 (Oxidation Number, Determination of Oxidation Number)",
  "Language of Chemistry: Assimilation 3 (Reaction, Equation, Unbalanced Chemical Equation, Hit and Trial Method, Limitations of a Balanced Chemical Equation)",
  "Atomic Structure: Assimilation 1 (Introduction, Dalton’s Atomic Theory and Limitations, Discovery of Electron – Cathode Rays, Properties of Cathode Rays, Discovery of Proton – Anode Rays, Properties of Anode Rays, Discovery of Neutron)",
  "Atomic Structure: Assimilation 2 (Thomson Atomic Model, Rutherford’s Scattering Experiment, Postulates of Rutherford’s Atomic Model, Defects of Rutherford Atomic Model, Bohr’s Atomic Model Postulates, Distribution of Electrons in Different Orbits)",
  "Classification of Elements: Assimilation 1 (Introduction, Necessity for Classification of Elements, Greek Classification, Lavoisier’s Classification, Dalton’s Classification, Dobereiner’s Classification, Newlands’ Law of Octaves, Lothar Meyer Classification, Mendeleev’s Classification)",
  "Chemical Bonding: Assimilation 1 (Introduction, Definition of Chemical Bonding, Cause of Chemical Combination, Lewis Symbols of Elements, Valency, Electronic Theory of Valency, Covalent Bond, Ionic Bond)",
  "Solutions: Assimilation 1 (Introduction, Types of Solutions, Based on Physical State of Solvent and Solute, Based on Amount of Solute, Based on Nature of Solvent, Based on Amount of Solute Dissolved, Based on Particle Size)",
  "The Chemistry of Laboratory: Assimilation 1 (Description of Chemicals Used in Laboratory)",
  "The Chemistry of Laboratory: Assimilation 2 (Activities in Laboratory)"
],
    "Biology": [
      "Nutrition in Plants",
      "Nutrition in Animals",
      "Respiration in Organisms",
      "Transportation in Animals and Plants",
      "Reproduction in Plants",
      "Forests: Our Lifeline",
      "Waste Disposal"
    ],
    "Biology NEET": [
      "Living World",
      "Cell - The Structural and Functional Unit of Life",
      "Cell Cycle and Cell Division",
      "Transport in Plants",
      "Plant Growth and Development",
      "Locomotion and Movement",
      "Sexual Reproduction in Plants",
      "Strategies in Enhancement Food Production",
      "Microbes in Human Welfare",
      "Human Health and Disease",
      "Ecosystem",
      "Bio Diversity"
    ],
    "Social": [
      "Our Universe and the Earth",
      "Forests",
      "Learning Through Maps",
      "Delhi Sulthanate",
      "Kakatiya Kingdom",
      "Vijayanagara Empire",
      "Equality in Indian Democracy",
      "State Government",
      "Our Country – India",
      "India’s Neighbors",
      "Rulers and Buildings",
      "Mobile and Settled Communities",
      "Popular Beliefs and Religious Debates"
    ]
  },

  "8th Class": {
    "Telugu": [
      "ఆత్మీయుడు",
      "పల్లకీ",
      "జ్ఞానం మిన్నయిన మూర్తి",
      "స్నేహం",
      "మా ఊరు",
      "కనుబడని దేవుడు",
      "స్వాతంత్ర్యం",
      "హరితహారం"
    ],
    "Hindi": [
      "ध्वनि",
      "लाख की चूड़ियाँ",
      "बस की यात्रा",
      "दीवानों की हस्ती",
      "चिट्ठियों की अनूठी दुनिया",
      "भगवान के डाकिए",
      "क्या निराश हुआ जाए",
      "यह सब से कठिन समय नहीं",
      "कबीर की साखियाँ",
      "कामचोर",
      "जब सिनेमा ने बोलना सीखा",
      "सुदामा चरित",
      "जहाँ चाह वहाँ राह"
    ],
    "English 1": [
      "My Mother",
      "Children, Speak Up!",
      "The Home Coming",
      "Unity in Diversity in India",
      "The World’s Most Dangerous Game",
      "Oliver Asks for More",
      "The Village Blacksmith",
      "A Hero"
    ],
    "English 2": [],
    "Math": [
      "Rational Numbers",
      "Linear Equations in One Variable",
      "Practical Geometry",
      "Squares and Square Roots",
      "Understanding Quadrilaterals",
      "Data Handling",
      "Cubes and Cube Roots",
      "Comparing Quantities",
      "Algebraic Expressions and Identities",
      "Visualizing Solid Shapes",
      "Mensuration",
      "Exponents and Powers",
      "Direct and Inverse Proportions",
      "Factorization",
      "Introduction to Graphs"
    ],
    "Math IIT": [
      "Number Theory - Basics",
      "Number Theory - LCM, HCF & Applications",
      "Progressions",
      "Linear Equations One & Two Variable",
      "Plane Geometry - Lines & Angles",
      "Plane Geometry - Triangles",
      "Quadratic Equations",
      "Exponents & Powers; Square Roots & Cube Roots",
      "Arithmetic-Direct & Inverse Proportion",
      "Arithmetic-Profit and Loss",
      "Algebraic Expressions - Basics",
      "Algebraic Expressions - Multiplications & Divisions",
      "Area of Plane Figures",
      "Polynomial - Factor, Remainder, Theorems",
      "Polynomials - Factorization",
      "Mensuration - Prism, Cube & Cuboid",
      "Mensuration - Cylinder, Cone, Sphere",
      "Trigonometry",
      "Coordinate Geometry-Distance & Section Formulae",
      "Coordinate Geometry - Area of Triangle & Quadrilateral",
      "Sets",
      "Logarithms"
    ],
    "Physics": [
      "Force and Pressure",
      "Friction",
      "Sound",
      "Light",
      "Stars and the Solar System"
    ],
    "Physics IIT & NEET": [
      "Units and Dimensions",
      "Motion in One Dimension",
      "Basics Mathematics",
      "Vectors",
      "Kinematics - 2D",
      "Newton's Laws of Motion",
      "Work-Energy and Power",
      "Circular Motion"
    ],
    "Chemistry": [
      "Synthetic Fibres and Plastics",
      "Chemical Effects of Electric Current",
      "Metals and Non-Metals",
      "Coal and Petroleum",
      "Combustion and Flame"
    ],
    "Chemistry IIT & NEET": [
      "Basic Principles of Chemistry",
      "Atomic Structure",
      "Classification of Elements",
      "Chemical Bonding",
      "Stoichiometry-I",
      "Gaseous State-I",
      "General Organic Chemistry-I",
      "Hydrogen & Its Compounds",
      "I A Group Elements"
    ],
    "Biology": [
      "Crop Production and Management",
      "Microorganisms: Friend and Foe",
      "Conservation of Plants and Animals",
      "Cell: Structure and Functions",
      "Reaching the Age of Adolescence",
      "Reproduction in Animals"
    ],
    "Biology NEET": [
      "Biological Classification",
      "Plant Kingdom",
      "Animal Kingdom",
      "Morphology Of Flowering Plants",
      "Structural Organization In Animals",
      "Anatomy Of Flowering Plants",
      "Mineral Nutrition",
      "Photosynthesis In Higher Plants",
      "Respiration In Plants",
      "Digestion And Absorption",
      "Breathing And Exchange Of Gases"
    ],
    "Social": [
      "Resources",
      "Land, Soil, Water, Natural Vegetation and Wildlife Resources",
      "How When and Where",
      "From Trade to Territory",
      "Ruling The Countryside",
      "Tibals and Dikus",
      "The Indian Constitution",
      "Understanding Secularism",
      "Judiciary",
      "Mineral and Power Resources",
      "Agriculture",
      "Industries",
      "Human Resources"
    ]
  },

  "9th Class": {
    "Telugu": [
      "స్వాగతం",
      "ప్రియమనసా",
      "పద్మనాభం కథ",
      "స్నేహ బంధం",
      "మన తెలంగాణ",
      "జ్ఞానం",
      "అభియాన్"
    ],
    "Hindi": [
      "दो बैलों की कथा",
      "ल्हासा की ओर",
      "उपभोक्तावाद की संस्कृति",
      "साँवले सपनों की याद",
      "मेरे बचपन के दिन",
      "एक फूल की चाह",
      "अन्नदाता",
      "कौन",
      "संकल्प"
    ],
    "English 1": [
      "The Duck and the Kangaroo",
      "The Snake and the Mirror",
      "The Happy Prince",
      "A Truly Beautiful Mind",
      "The Road Not Taken",
      "Wind",
      "The Little Girl",
      "Rain on the Roof",
      "Weathering the Storm in Ersama"
    ],
    "English 2": [],
    "Math": [
      "Number Systems",
      "Polynomials",
      "Coordinate Geometry",
       "Triangles",
       "Linear Equations in Two Variables",
      "Introduction to Euclid’s Geometry",
      "Lines and Angles",
      "Quadrilaterals",
      "Areas of Parallelograms and Triangles",
      "Circles",
      "Constructions",
      "Heron’s Formula",
      "Surface Areas and Volumes",
      "Statistics",
      "Probability"
    ],
    "Math IIT": [
      "Theory of Numbers - Basics",
      "Theory of Numbers - Congruence of Integers",
      "Surds",
      "Theory of Equations",
      "Geometry - Triangles",
      "Geometry - Similar Triangles",
      "Geometry - Circles",
      "Matrices",
      "Determinants",
      "Complex Numbers",
      "Trigonometry - Ratios and Identities",
       "Trigonometry - Multiples and Submultiples",
      "Properties of Triangles - Sine, Cosine, Projection Rules",
      "Properties of Triangles - Napier, Half Angle, Mollweide Rules",
      "Coordinate Geometry - The Straight Lines",
      "Coordinate Geometry - Foot and Image of Point",
      "Permutations",
      "Combinations",
      "Binomial Theorem",
      "Progressions - A.P and G.P",
      "Progressions - H.P and A.G.P",
      "Probability"
    ],
    "Physics": [
      "Motion",
      "Force and Laws of Motion",
      "Gravitation",
      "Work and Energy",
      "Sound"
    ],
    "Physics IIT & NEET": [
      "Basics",
      "Centre of Mass",
      "Collisions",
      "Gravitation",
      "Mechanical Properties of Solids",
      "Mechanical Properties of Fluids",
      "Viscosity",
      "Surface Tension",
      "Expansion of Solids",
      "Expansion of Liquids and Gases",
      "Calorimetry",
      "Oscillations"
    ],
    "Chemistry": [
      "Matter in Our Surroundings",
      "Is Matter Around Us Pure?",
      "Atoms and Molecules",
      "Structure of the Atom"
    ],
    "Chemistry IIT & NEET": [
      "Gaseous State - II",
      "Stoichiometry - II",
      "Chemical Equilibrium",
      "Dilute Solutions",
      "Ionic Equilibrium",
      "Chemical Kinetics",
      "General Organic Chemistry - I"
    ],
    "Biology": [
      "The Fundamental Unit of Life (Cell)",
      "Tissues",
      "Diversity in Living Organisms",
      "Why Do We Fall Ill?",
      "Natural Resources",
      "Improvement in Food Resources"
    ],
    "Biology NEET": [
      "Origin & Evolution",
      "How Do Organisms Reproduce",
      "Control & Coordination",
      "Life Process - Nutrition (Part 1)",
      "Life Process - Nutrition (Part 2)",
      "Genetics",
      "Our Environment",
      "Management of Natural Resources"
    ],
    "Social": [
      "India: Size and Location",
      "Socialism in Europe and the Russian Revolution",
      "What is Democracy? why is Democracy?",
      "Constitutional Design",
      "People as Resource",
      "The French revolution",
      " A Story of Village Palampur",
      "Physical Features of India",
      "Drainage",
      "Climate",
      "Natural Vegetation and Wildlife",
      "Population"
    ]
  },
  "10th Class": {
    "Telugu": [
      "మన ఊరు – మనం",
      "జగమెరిగిన మనిషి",
      "జ్ఞానం",
      "స్వతంత్రోద్యమ కథలు",
      "నీలం – జ్ఞానం",
      "పాట – స్వేచ్ఛ",
      "శ్రీరాముడు",
      "విజయగాథ"
    ],
    "Hindi": [
      "सूरदास – पद",
      "तुलसीदास – दोहे",
      "जयशंकर प्रसाद – सूर के पद",
      "सूर्यकांत त्रिपाठी 'निराला' – वह तोड़ती पत्थर",
      "नागार्जुन – जीवन में संगीत",
      "गिरिजाकुमार माथुर – तोप",
      "रवींद्रनाथ ठाकुर – आत्मत्राण",
      "सैयद अली जाफ़री – छोटे-से जीवन की पहचान",
      "लीलाधर मंडलोई – पतझर में टूटी पत्तियाँ"
    ],
    "English 1": [
      "A Letter to God",
      "Nelson Mandela: Long Walk to Freedom",
      "Two Stories About Flying",
      "From the Diary of Anne Frank",
      "The Hundred Dresses – I",
      "The Hundred Dresses – II",
      "Glimpses of India",
      "Mijbil the Otter",
      "Madam Rides the Bus",
      "The Sermon at Benares",
      "The Proposal"
    ],
    "English 2": [],
    "Math": [
      "Real Numbers",
      "Polynomials",
      "Pair of Linear Equations in Two Variables",
      "Quadratic Equations",
      "Arithmetic Progressions",
      "Triangles",
      "Coordinate Geometry",
      "Introduction to Trigonometry",
      "Applications of Trigonometry",
      "Circles",
      "Constructions",
      "Areas Related to Circles",
      "Surface Areas and Volumes",
      "Statistics",
      "Probability"
    ],
    "Physics": [
      "Chemical Reactions and Equations",
      "Acids, Bases and Salts",
      "Metals and Non-Metals",
      "Carbon and Its Compounds",
      "Periodic Classification of Elements",
      "Light – Reflection and Refraction",
      "Human Eye and Colourful World",
      "Electricity",
      "Magnetic Effects of Electric Current"
    ],
    "Chemistry": [
      "Chemical Reactions and Equations",
      "Acids, Bases and Salts",
      "Metals and Non-Metals",
      "Carbon and Its Compounds",
      "Periodic Classification of Elements"
    ],
    "Biology": [
      "Life Processes",
      "Control and Coordination",
      "How Do Organisms Reproduce?",
      "Heredity and Evolution",
      "Our Environment",
      "Management of Natural Resources"
    ],
    "Social": [
      "The Rise of Nationalism in Europe",
      "Nationalism in India",
      "The Making of a Global World",
      "The Age of Industrialization",
      "Print Culture and the Modern World",
      "Resources and Development",
      "Forest and Wildlife Resources",
      "Water Resources",
      "Agriculture",
      "Minerals and Energy Resources",
      "Manufacturing Industries",
      "Lifelines of National Economy",
      "Power Sharing",
      "Federalism",
      "Democracy and Diversity",
      "Gender, Religion and Caste",
      "Popular Struggles and Movements",
      "Political Parties",
      "Outcomes of Democracy",
      "Challenges to Democracy",
      "Development",
      "Sectors of the Indian Economy",
      "Money and Credit",
      "Globalization and the Indian Economy",
      "Consumer Rights"
    ]
  }
};
